version: 2
jobs:
  build:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "package.json" }}
          - yarn-v3-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - yarn.lock
          key: yarn-v3-{{ checksum "package.json" }}

  unit_test:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "package.json" }}
          - yarn-v3-

      - run: yarn install

      - run:
          name: Unit Test
          command: yarn test

  integration_test:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "package.json" }}
          - yarn-v3-

      - run: yarn install
      - run:
          name: Integration Test
          command: SAUCE_USERNAME=$SAUCE_USERNAME SAUCE_KEY=$SAUCE_KEY yarn test:integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /\w+\/.*/

      - unit_test:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/

      - integration_test:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/
