version: 2
jobs:
  build:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v2-{{ checksum "package.json" }}
          - yarn-v2-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - yarn.lock
          key: yarn-v2-{{ checksum "package.json" }}

      - run: mkdir -p /tmp/workspace

  test:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v2-{{ checksum "package.json" }}
          - yarn-v2-

      - run: yarn install

      - run:
          name: Unit Test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/
